/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.galaxy.ui;

import com.galaxy.dao.HoaDonDAO;
import com.galaxy.entity.HoaDon;
import com.galaxy.utils.Auth;
import com.galaxy.utils.MsgBox;
import com.galaxy.utils.XDate;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class HoaDonJdialog1 extends javax.swing.JPanel {

    /**
     * Creates new form HoaDonJdialog1
     */
    public HoaDonJdialog1() {
        initComponents();
        this.init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton17 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtNgayLapHD = new javax.swing.JTextField();
        txtMaKH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtMaSP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDonGia = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtThanhtien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnMoi = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        backgroud = new javax.swing.JLabel();

        setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("HÓA ĐƠN");
        add(jLabel2);
        jLabel2.setBounds(520, 20, 170, 29);
        add(jTextField3);
        jTextField3.setBounds(190, 80, 140, 22);

        jButton18.setText("Tìm Kiếm");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        add(jButton18);
        jButton18.setBounds(340, 80, 110, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(240, 240, 240));
        jLabel4.setText("Tìm kiếm theo: ID");
        add(jLabel4);
        jLabel4.setBounds(50, 80, 131, 20);

        jButton17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton17.setText("Xuất Excel");
        add(jButton17);
        jButton17.setBounds(820, 70, 150, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mã HĐ");
        add(jLabel1);
        jLabel1.setBounds(50, 140, 60, 20);
        add(txtMaHD);
        txtMaHD.setBounds(170, 140, 200, 22);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ngày lập HĐ");
        add(jLabel3);
        jLabel3.setBounds(50, 170, 89, 20);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mã KH");
        add(jLabel8);
        jLabel8.setBounds(50, 200, 45, 20);
        add(txtNgayLapHD);
        txtNgayLapHD.setBounds(170, 170, 200, 22);
        add(txtMaKH);
        txtMaKH.setBounds(170, 200, 200, 22);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mã NV");
        add(jLabel9);
        jLabel9.setBounds(420, 140, 46, 20);
        add(txtMaNV);
        txtMaNV.setBounds(490, 140, 210, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mã SP");
        add(jLabel5);
        jLabel5.setBounds(420, 170, 43, 20);
        add(txtMaSP);
        txtMaSP.setBounds(490, 170, 210, 22);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Đơn giá");
        add(jLabel11);
        jLabel11.setBounds(420, 200, 55, 20);
        add(txtDonGia);
        txtDonGia.setBounds(490, 200, 210, 22);

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Số lượng");
        add(jLabel12);
        jLabel12.setBounds(720, 140, 64, 20);
        add(txtSoLuong);
        txtSoLuong.setBounds(810, 140, 200, 22);

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Thành tiền");
        add(jLabel13);
        jLabel13.setBounds(720, 170, 76, 20);
        add(txtThanhtien);
        txtThanhtien.setBounds(810, 170, 200, 22);

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MÃ HĐ", "NGÀY LẬP HĐ", "MÃ KH", "MÃ NV", "Mã SP", "ĐƠN GIÁ", "SỐ LƯỢNG", "THÀNH TIỀN"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblHoaDon.setRowHeight(25);
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 230, 1030, 320);

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        add(btnThem);
        btnThem.setBounds(40, 580, 70, 30);

        btnSua.setText("Sửa");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });
        add(btnSua);
        btnSua.setBounds(130, 580, 70, 30);

        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        add(btnXoa);
        btnXoa.setBounds(220, 580, 60, 30);

        btnMoi.setText("Mới");
        btnMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMoiActionPerformed(evt);
            }
        });
        add(btnMoi);
        btnMoi.setBounds(310, 580, 70, 30);

        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });
        add(btnFirst);
        btnFirst.setBounds(760, 570, 60, 30);

        btnPrev.setText("<<");
        btnPrev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevActionPerformed(evt);
            }
        });
        add(btnPrev);
        btnPrev.setBounds(850, 570, 60, 30);

        btnNext.setText(">>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });
        add(btnNext);
        btnNext.setBounds(930, 570, 60, 30);

        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });
        add(btnLast);
        btnLast.setBounds(1010, 570, 60, 30);

        backgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/galaxy/icon/blue-galaxy.jpg"))); // NOI18N
        backgroud.setText("jLabel3");
        add(backgroud);
        backgroud.setBounds(0, 0, 1360, 900);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton18ActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblHoaDon.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.insert();
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        this.update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.delete();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMoiActionPerformed
        // TODO add your handling code here:
        this.clearForm();
    }//GEN-LAST:event_btnMoiActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        // TODO add your handling code here:
        this.first();
    }//GEN-LAST:event_btnFirstActionPerformed

    private void btnPrevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevActionPerformed
        // TODO add your handling code here:
        this.prev();
    }//GEN-LAST:event_btnPrevActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        this.next();
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        // TODO add your handling code here:
        this.last();
    }//GEN-LAST:event_btnLastActionPerformed
    HoaDonDAO dao = new HoaDonDAO();
    int row = -1;

    void init() {
        this.fillTable();
        this.updateStatus();
    }

    void fillTable() {
        DefaultTableModel model = (DefaultTableModel) tblHoaDon.getModel();
        model.setRowCount(0);
        try {
            List<HoaDon> list = dao.selectAll();
            for (HoaDon hd : list) {
                Object[] row = {
                    hd.getMaHD(),
                    hd.getNgayLapHD(),
                    hd.getMaKH(),
                    hd.getMaNV(),
                    hd.getMaSP(),
                    hd.getDonGia(),
                    hd.getSoLuong(),
                    hd.getThanhTien()
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn dữ liệu!");
        }
    }

    void insert() {
        HoaDon hd = this.getForm();
        try {
            dao.insert(hd);
            this.fillTable();
            this.clearForm();
            MsgBox.alert(this, "Thêm mới thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Thêm mới thất bại!");
        }
    }

    void update() {
        HoaDon hd = this.getForm();
        try {
            dao.update(hd);
            this.fillTable();
            MsgBox.alert(this, "Cập nhật thành công!");
        } catch (Exception e) {
            MsgBox.alert(this, "Cập nhật thất bại!");
        }
    }

    void delete() {
        if (!Auth.isManager()) {
            MsgBox.alert(this, "Bạn không có quyền xóa hóa đơn!");
        } else {
            String makh = txtMaHD.getText();
            if (MsgBox.confirm(this, "Bạn thực sự muốn xóa hóa đơn này?")) {
                try {
                    dao.delete(makh);
                    this.fillTable();
                    this.clearForm();
                    MsgBox.alert(this, "Xóa thành công!");
                } catch (Exception e) {
                    MsgBox.alert(this, "Xóa thất bại!");
                }
            }
        }
    }

    void clearForm() {
        HoaDon hd = new HoaDon();
        this.setForm(hd);
        this.row = -1;
        this.updateStatus();
    }

    void edit() {
        String mahd = (String) tblHoaDon.getValueAt(this.row, 0);
        HoaDon hd = dao.selectById(mahd);
        this.setForm(hd);
        this.updateStatus();
    }

    void setForm(HoaDon hd) {
        txtMaHD.setText(hd.getMaHD());
        txtNgayLapHD.setText(XDate.toString(hd.getNgayLapHD(), "MM/dd/yyyy"));
        txtMaKH.setText(hd.getMaKH());
        txtMaNV.setText(hd.getMaKH());
        txtMaSP.setText(hd.getMaSP());
        txtDonGia.setText(String.valueOf(hd.getDonGia()));
        txtSoLuong.setText(String.valueOf(hd.getSoLuong()));
        txtThanhtien.setText(String.valueOf(hd.getThanhTien()));

    }

    HoaDon getForm() {
        HoaDon hd = new HoaDon();
        hd.setMaHD(txtMaHD.getText());
        hd.setNgayLapHD(XDate.toDate(txtNgayLapHD.getText(), "MM/dd/yyyy"));
        hd.setMaKH(txtMaKH.getText());
        hd.setMaNV(txtMaNV.getText());
        hd.setMaSP(txtSoLuong.getText());
        hd.setDonGia(Double.parseDouble(txtDonGia.getText()));
        hd.setSoLuong(Integer.parseInt(txtSoLuong.getText()));
        hd.setThanhTien(Double.parseDouble(txtThanhtien.getText()));
        return hd;
    }

    void first() {
        this.row = 0;
        this.edit();
    }

    void prev() {
        if (this.row > 0) {
            this.row--;
            this.edit();
        }
    }

    void next() {
        if (this.row < tblHoaDon.getRowCount() - 1) {
            this.row++;
            this.edit();
        }
    }

    void last() {
        this.row = tblHoaDon.getRowCount() - 1;
        this.edit();
    }

    void updateStatus() {
        boolean edit = (this.row >= 0);
        boolean first = (this.row == 0);
        boolean last = (this.row == tblHoaDon.getRowCount() - 1);
        txtMaHD.setEditable(!edit);
        btnThem.setEnabled(!edit);
        btnSua.setEnabled(edit);
        btnXoa.setEnabled(edit);

        btnFirst.setEnabled(edit && !first);
        btnPrev.setEnabled(edit && !first);
        btnNext.setEnabled(edit && !last);
        btnLast.setEnabled(edit && !last);
    }

    // Quyên làm tương tự
    boolean isValidated() {
        HoaDon hd = this.getForm();
        if (hd.getMaHD().length() == 0) {
            MsgBox.alert(this, "Không để trống mã hóa đơn!");
        } else if (String.valueOf(hd.getNgayLapHD()).length() == 0) {
            MsgBox.alert(this, "Không để trống ngày lập hóa đơn!");
        } else if (hd.getMaKH().length() == 0) {
            MsgBox.alert(this, "Không để trống mã khách hàng!");
        } else if (hd.getMaNV().length() == 0) {
            MsgBox.alert(this, "Không để trống mã nhân viên!");
        } else if (hd.getMaSP().length() == 0) {
            MsgBox.alert(this, "Không để trống mã sản phẩm!");
        } else if (hd.getDonGia() == 0) {
            MsgBox.alert(this, "Không để trống đơn giá!");
        } else if (hd.getSoLuong() == 0) {
            MsgBox.alert(this, "Không để trống số lượng!");
        } else if (hd.getThanhTien() == 0) {
            MsgBox.alert(this, "Không để trống thành tiền!");
        } else {
            return true;
        }
        return false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroud;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnMoi;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTextField txtDonGia;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtMaKH;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMaSP;
    private javax.swing.JTextField txtNgayLapHD;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtThanhtien;
    // End of variables declaration//GEN-END:variables
}
